export const QuarkGroupAbi = {
  address: "0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4",
  name: "group",
  friends: [],
  exposed_functions: [
    {
      name: "pay_ai",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: ["&signer", "&signer", "0x1::string::String", "u64"],
      return: [],
    },
    {
      name: "claim_reward_v1",
      visibility: "private",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: [
        "&signer",
        "&signer",
        "address",
        "0x1::string::String",
        "0x1::string::String",
      ],
      return: [],
    },
    {
      name: "claim_reward_v2",
      visibility: "private",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "&signer",
        "address",
        "address",
        "0x1::string::String",
        "0x1::string::String",
      ],
      return: [],
    },
    {
      name: "create_group",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "&signer", "0x1::string::String"],
      return: [],
    },
    {
      name: "create_group_dao_v1",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: [
        "&signer",
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "vector<0x1::string::String>",
        "u64",
        "u64",
      ],
      return: [],
    },
    {
      name: "create_group_dao_v2",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "vector<0x1::string::String>",
        "address",
        "u64",
        "u64",
      ],
      return: [],
    },
    {
      name: "create_pool_reward_v1",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: [
        "&signer",
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "u64",
        "u64",
      ],
      return: [],
    },
    {
      name: "create_pool_reward_v2",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "address",
        "u64",
        "u64",
      ],
      return: [],
    },
    {
      name: "exist_group_dao_v1",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String"],
      return: ["bool"],
    },
    {
      name: "exist_group_dao_v2",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String"],
      return: ["bool"],
    },
    {
      name: "exist_group_id",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String"],
      return: ["bool"],
    },
    {
      name: "exist_group_user_choice_v1",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String", "address"],
      return: ["bool"],
    },
    {
      name: "exist_group_user_choice_v2",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String", "address"],
      return: ["bool"],
    },
    {
      name: "get_group_account",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String"],
      return: ["address"],
    },
    {
      name: "get_group_dao_v1",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String"],
      return: [
        "0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::GroupDaoV1View",
      ],
    },
    {
      name: "get_group_dao_v2",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String"],
      return: [
        "0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::GroupDaoV2View",
      ],
    },
    {
      name: "get_group_daos_v1",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String"],
      return: [
        "0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::GroupDaosV1View",
      ],
    },
    {
      name: "get_group_daos_v2",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String"],
      return: [
        "0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::GroupDaosV2View",
      ],
    },
    {
      name: "get_group_user_choice_v1",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String", "address"],
      return: [
        "0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::UserChoiceView",
      ],
    },
    {
      name: "get_group_user_choice_v2",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String", "address"],
      return: [
        "0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::UserChoiceView",
      ],
    },
    {
      name: "get_group_user_choices_v1",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String"],
      return: [
        "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::UserChoiceView>",
      ],
    },
    {
      name: "get_group_user_choices_v2",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String"],
      return: [
        "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::UserChoiceView>",
      ],
    },
    {
      name: "get_pool_reward_v1",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String"],
      return: ["u64", "address", "u64", "vector<address>", "address"],
    },
    {
      name: "get_pool_reward_v2",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String", "0x1::string::String"],
      return: ["u64", "address", "u64", "vector<address>", "address"],
    },
    {
      name: "get_pools_rewards_v1",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String"],
      return: [
        "0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::PoolsRewardsV1View",
      ],
    },
    {
      name: "get_pools_rewards_v2",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::string::String"],
      return: [
        "0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::PoolsRewardsV2View",
      ],
    },
    {
      name: "pay_users_v1",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: [
        "&signer",
        "&signer",
        "0x1::string::String",
        "u64",
        "vector<address>",
      ],
      return: [],
    },
    {
      name: "pay_users_v2",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "&signer",
        "0x1::string::String",
        "u64",
        "address",
        "vector<address>",
      ],
      return: [],
    },
    {
      name: "vote_group_dao_v1",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: ["&signer", "0x1::string::String", "0x1::string::String", "u64"],
      return: [],
    },
    {
      name: "vote_group_dao_v2",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "u64",
        "address",
      ],
      return: [],
    },
  ],
  structs: [
    {
      name: "Group",
      is_native: false,
      is_event: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        { name: "group_id", type: "0x1::string::String" },
        { name: "account", type: "address" },
      ],
    },
    {
      name: "PayAiEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "group", type: "address" },
        { name: "amount", type: "u64" },
        { name: "currency", type: "address" },
        { name: "recipient", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "CreateGroupDaoEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "group", type: "address" },
        { name: "dao_id", type: "0x1::string::String" },
        { name: "choices", type: "vector<0x1::string::String>" },
        { name: "created_at", type: "u64" },
        { name: "from", type: "u64" },
        { name: "to", type: "u64" },
      ],
    },
    {
      name: "CreateGroupEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "group", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "GroupDaoV1",
      is_native: false,
      is_event: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        { name: "dao_id", type: "0x1::string::String" },
        { name: "group_id", type: "0x1::string::String" },
        { name: "choices", type: "vector<0x1::string::String>" },
        { name: "choices_weights", type: "vector<u64>" },
        {
          name: "user_choices",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::UserChoice>",
        },
        { name: "coin_type", type: "address" },
        { name: "from", type: "u64" },
        { name: "to", type: "u64" },
      ],
    },
    {
      name: "GroupDaoV1View",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        { name: "dao_id", type: "0x1::string::String" },
        { name: "group_id", type: "0x1::string::String" },
        { name: "choices", type: "vector<0x1::string::String>" },
        { name: "choices_weights", type: "vector<u64>" },
        {
          name: "user_choices",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::UserChoiceView>",
        },
        { name: "coin_type", type: "address" },
        { name: "from", type: "u64" },
        { name: "to", type: "u64" },
      ],
    },
    {
      name: "GroupDaoV2",
      is_native: false,
      is_event: false,
      abilities: ["store"],
      generic_type_params: [],
      fields: [
        { name: "dao_id", type: "0x1::string::String" },
        { name: "group_id", type: "0x1::string::String" },
        { name: "choices", type: "vector<0x1::string::String>" },
        { name: "choices_weights", type: "vector<u64>" },
        {
          name: "user_choices",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::UserChoice>",
        },
        { name: "currency", type: "address" },
        { name: "from", type: "u64" },
        { name: "to", type: "u64" },
      ],
    },
    {
      name: "GroupDaoV2View",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        { name: "dao_id", type: "0x1::string::String" },
        { name: "group_id", type: "0x1::string::String" },
        { name: "choices", type: "vector<0x1::string::String>" },
        { name: "choices_weights", type: "vector<u64>" },
        {
          name: "user_choices",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::UserChoiceView>",
        },
        { name: "currency", type: "address" },
        { name: "from", type: "u64" },
        { name: "to", type: "u64" },
      ],
    },
    {
      name: "GroupDaosV1",
      is_native: false,
      is_event: false,
      abilities: ["store", "key"],
      generic_type_params: [],
      fields: [
        {
          name: "daos",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::GroupDaoV1>",
        },
      ],
    },
    {
      name: "GroupDaosV1View",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        {
          name: "daos",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::GroupDaoV1View>",
        },
      ],
    },
    {
      name: "GroupDaosV2",
      is_native: false,
      is_event: false,
      abilities: ["store", "key"],
      generic_type_params: [],
      fields: [
        {
          name: "daos",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::GroupDaoV2>",
        },
      ],
    },
    {
      name: "GroupDaosV2View",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        {
          name: "daos",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::GroupDaoV2View>",
        },
      ],
    },
    {
      name: "GroupPayToUsersV1Event",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "group", type: "address" },
        { name: "amount", type: "u64" },
        { name: "recipients", type: "vector<address>" },
        { name: "currency", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "GroupPayToUsersV2Event",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "group", type: "address" },
        { name: "amount", type: "u64" },
        { name: "recipients", type: "vector<address>" },
        { name: "currency", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "GroupSigner",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [{ name: "signer_cap", type: "0x1::account::SignerCapability" }],
    },
    {
      name: "Groups",
      is_native: false,
      is_event: false,
      abilities: ["store", "key"],
      generic_type_params: [],
      fields: [
        {
          name: "groups",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::Group>",
        },
      ],
    },
    {
      name: "PoolRewardHolder",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [{ name: "extend_ref", type: "0x1::object::ExtendRef" }],
    },
    {
      name: "PoolRewardV1",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store", "key"],
      generic_type_params: [],
      fields: [
        { name: "pool_id", type: "0x1::string::String" },
        { name: "reward_amount", type: "u64" },
        { name: "reward_token", type: "address" },
        { name: "total_users", type: "u64" },
        { name: "claimed_users", type: "vector<address>" },
        { name: "holder_object", type: "address" },
      ],
    },
    {
      name: "PoolRewardV1View",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        { name: "pool_id", type: "0x1::string::String" },
        { name: "reward_amount", type: "u64" },
        { name: "reward_token", type: "address" },
        { name: "total_users", type: "u64" },
        { name: "claimed_users", type: "vector<address>" },
        { name: "holder_object", type: "address" },
      ],
    },
    {
      name: "PoolRewardV2",
      is_native: false,
      is_event: false,
      abilities: ["drop", "store", "key"],
      generic_type_params: [],
      fields: [
        { name: "pool_id", type: "0x1::string::String" },
        { name: "reward_amount", type: "u64" },
        { name: "reward_token", type: "address" },
        { name: "currency", type: "address" },
        { name: "total_users", type: "u64" },
        { name: "claimed_users", type: "vector<address>" },
        { name: "holder_object", type: "address" },
      ],
    },
    {
      name: "PoolRewardV2View",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        { name: "pool_id", type: "0x1::string::String" },
        { name: "reward_amount", type: "u64" },
        { name: "reward_token", type: "address" },
        { name: "currency", type: "address" },
        { name: "total_users", type: "u64" },
        { name: "claimed_users", type: "vector<address>" },
        { name: "holder_object", type: "address" },
      ],
    },
    {
      name: "PoolsRewardsV1",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop", "store", "key"],
      generic_type_params: [],
      fields: [
        {
          name: "pools",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::PoolRewardV1>",
        },
      ],
    },
    {
      name: "PoolsRewardsV1View",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        {
          name: "pools",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::PoolRewardV1View>",
        },
      ],
    },
    {
      name: "PoolsRewardsV2",
      is_native: false,
      is_event: false,
      abilities: ["drop", "store", "key"],
      generic_type_params: [],
      fields: [
        {
          name: "pools",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::PoolRewardV2>",
        },
      ],
    },
    {
      name: "PoolsRewardsV2View",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        {
          name: "pools",
          type: "vector<0xeabd22210b1b985d0c5ec1e4902608f00b92461486d97c5bba29479c70534a4::group::PoolRewardV2View>",
        },
      ],
    },
    {
      name: "UserChoice",
      is_native: false,
      is_event: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "dao_id", type: "0x1::string::String" },
        { name: "choice_id", type: "u64" },
        { name: "vote_weight", type: "u64" },
        { name: "user", type: "address" },
      ],
    },
    {
      name: "UserChoiceView",
      is_native: false,
      is_event: false,
      abilities: ["copy", "drop"],
      generic_type_params: [],
      fields: [
        { name: "dao_id", type: "0x1::string::String" },
        { name: "choice_id", type: "u64" },
        { name: "vote_weight", type: "u64" },
        { name: "user", type: "address" },
      ],
    },
    {
      name: "VoteGroupDaoV1Event",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "group", type: "address" },
        { name: "dao_id", type: "0x1::string::String" },
        { name: "choice_id", type: "u64" },
        { name: "vote_weight", type: "u64" },
        { name: "user", type: "address" },
        { name: "coin_type", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "VoteGroupDaoV2Event",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "group", type: "address" },
        { name: "dao_id", type: "0x1::string::String" },
        { name: "choice_id", type: "u64" },
        { name: "vote_weight", type: "u64" },
        { name: "user", type: "address" },
        { name: "currency", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
  ],
} as const;
