export const QuarkUserAbi = {
  address: "0x2033b72957c2f0b66cf5be479a2aa098d5bf18c36477907eba8be39435f2811",
  name: "user_v5",
  friends: [],
  exposed_functions: [
    {
      name: "create_account",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "0x1::string::String"],
      return: [],
    },
    {
      name: "exists_resource_account",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["bool"],
    },
    {
      name: "get_resource_account",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["address"],
      return: ["address"],
    },
    {
      name: "get_token_address",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["0x1::option::Option<address>"],
    },
    {
      name: "pay_ai",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: ["&signer", "&signer", "address", "u64"],
      return: [],
    },
    {
      name: "pay_to_users_v1",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: ["&signer", "&signer", "address", "u64", "vector<address>"],
      return: [],
    },
    {
      name: "pay_to_users_v2",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "&signer",
        "address",
        "u64",
        "address",
        "vector<address>",
      ],
      return: [],
    },
    {
      name: "set_coin_address",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: ["&signer"],
      return: [],
    },
    {
      name: "withdraw_funds_v1",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [{ constraints: [] }],
      params: ["&signer", "u64"],
      return: [],
    },
    {
      name: "withdraw_funds_v2",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "u64", "address"],
      return: [],
    },
  ],
  structs: [
    {
      name: "Account",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        { name: "telegram_id", type: "0x1::string::String" },
        { name: "signer_cap", type: "0x1::account::SignerCapability" },
      ],
    },
    {
      name: "Config",
      is_native: false,
      is_event: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [{ name: "coin_addr", type: "0x1::option::Option<address>" }],
    },
    {
      name: "CreateAccountEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "owner", type: "address" },
        { name: "user", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "PayAiEvent",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "user", type: "address" },
        { name: "amount", type: "u64" },
        { name: "currency", type: "address" },
        { name: "recipient", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "PayToUsersV1Event",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "user", type: "address" },
        { name: "amount", type: "u64" },
        { name: "recipients", type: "vector<address>" },
        { name: "currency", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "PayToUsersV2Event",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "user", type: "address" },
        { name: "amount", type: "u64" },
        { name: "recipients", type: "vector<address>" },
        { name: "currency", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "WithdrawFundsV1Event",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "user", type: "address" },
        { name: "amount", type: "u64" },
        { name: "currency", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
    {
      name: "WithdrawFundsV2Event",
      is_native: false,
      is_event: true,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "user", type: "address" },
        { name: "amount", type: "u64" },
        { name: "currency", type: "address" },
        { name: "created_at", type: "u64" },
      ],
    },
  ],
} as const;
